### ISSUE TITLE
Website notes and recommendations

### ISSUE THREAD

**Issue by OmerSapir** [ShaharGarin/shahar_assignments#1]
Hi Shahar,
I really like your website!
especially the composition of your avatar running alongside the content, and the 'cool guy' reference.

As you mentioned you play video games, what are your favorite games?

@szabgab

**Comment by ShaharGarin** [comment]
Thanks for the feedback.

My favorite games are the Final Fantasy VII Remakes (the pictures on the website are from the newest one).
