### ISSUE TITLE
Your cool websit

### ISSUE THREAD

**Issue by MeirSylman** [ShaharGarin/shahar_assignments#2]
Hi Sahar!

I enjoyed seeing your website. The picture you chose looks special because it combines figures from a war game, yet the picture looks so peaceful.

If it's fine with you, maybe you could add some more details about the game's philosophy?

See you at the next lecture of the Python course with @szabgab.

Meir

**Comment by ShaharGarin** [comment]
Hi. Thank for the feedback. I'm still playing the game at the moment. Maybe once I'm done I'll add a page with more details on it.
